### ISSUE TITLE
Error plotting

### ISSUE THREAD

**Issue by marieediaas** [bretthandrews/flexCE#9]
Hello!

I'm just starting to use flexCE and I'm getting an error that may be very simple to solve, but I haven't managed it myself. Here's the line of code:

 File "/home/user/flexce/flexCE/plot/plot_xfe_feh.py", line 35, in <module>
    import plot.utils as putils
ModuleNotFoundError: No module named 'plot'

Can you give me some help?

**Comment by bretthandrews** [comment]
Hmmm...I'm not 100% sure what's going wrong for your setup. If I had to guess, the top-level flexce directory is not in your python path by line 35 when plot_xfe_feh.py is trying to import plot.utils. I would try to run plot_xfe_feh.py from its directory (if you're trying to run it from somewhere else) and if that fails, then try to print out the python path to make sure that the top-level flexce directory is there.

**Comment by marieediaas** [comment]
Thanks
